### ISSUE TITLE
Research, Analysis, and Design of System Tests

### ISSUE THREAD

**Issue by Rebits** [wazuh/qa-system-framework#26]
## Description

System tests are a type of software testing performed on a complete and integrated system to evaluate its compliance with specified requirements. These tests focus on verifying that the system functions as expected and that all its components work together correctly. The purpose of system testing is to validate the system's behavior and performance in a real-world environment.

Regarding Wazuh testing, these system tests will differ from the E2E tests in that they will not test the indexer or the dashboard. Instead, they will solely focus on testing the manager and agent components, as well as their integration with cloud environments.

**Examples of system tests:**

- Monitoring a file on the agent generates the expected alerts in the manager's alert.log file.
- The software installed on an agent is correctly detected and stored in the expected manager's database.
- In a clustered environment with an agent, only the expected multi-groups are regenerated when a new group file is created in the environment.
- Agents are successfully updated using WPK
- All insecure configurations of an agent are correctly detected with SCA (Security Configuration Assessment), and alerts are generated correctly in the manager `alerts.log`.
 
Given all these characteristics and requirements, it is necessary to investigate the current state of system testing, as well as the approach adopted by the ongoing development and other possible solutions to implement these system tests.

### To Do
- [x] [Conduct an examination of the current system tests](https://github.com/wazuh/qa-system-framework/issues/26#issuecomment-1562500439).
- [x] [Conduct an analysis of the current system test framework in progress](https://github.com/wazuh/qa-system-framework/issues/26#issuecomment-1563195815).
- [x] Explore alternative approaches to the previous system test framework.
    - [x] [TerraTest](https://github.com/wazuh/qa-system-framework/issues/26#issuecomment-1568182610)
    - [x] [KitchenCI](https://github.com/wazuh/qa-system-framework/issues/26#issuecomment-1568245679)
- [x] [Propose improvement to the current system tests approach
](https://github.com/wazuh/qa-system-framework/issues/26#issuecomment-1569892309)

**Comment by Rebits** [comment]
## Current system test framework in progress


The basic idea is to separate, after this change, starting from a structure similar to the system tests proposed in the QA repository but addressing their weaknesses. For this purpose, it has been proposed to decouple the tests from the Docker ecosystem, allowing them to be launched in any environment provided by an Ansible inventory. This will enable us to take advantage of the automation possibilities in Jenkins, allowing the tests to be executed on all the operating systems supported by Wazuh.

Furthermore, there is a plan to improve the current framework by enriching it to include higher-level functions that allow for a more organic interaction with the Wazuh environment. At the same time, additional functionalities will be incorporated into the framework to facilitate development and error reporting, such as a debugging system and an evidence collection fixture.

To achieve these objectives, a series of libraries were created in Jenkins, called WazuhQAEnvironment, which enable dynamic deployment and provisioning of instances according to the specific needs of each test. These instances can be of any operating system, including EC2, ECS, or local server instances in Vagrant.

This will make it possible to have a single process in Jenkins to deploy and provision instances, reducing the complexity of the pipelines and facilitating development.

Once the instances are deployed and provisioned, the system tests specified by pipeline parameters will be launched from the Jenkins node, using a custom inventory generated by the library itself to access the remote instances.

**Comment by roronoasins** [comment]
## Approach using just ansible

Currently we have some pipelines that could help us to deploy instances (Deployer pipeline) and provision them using `wazuh-ansible`. Besides, we should create our own ansible repo so we can add/fix or whatever we need about new systems/components without rely on another repo.

```mermaid
graph LR;
JenkinsNode -->|Deploy|dep((Deployer));
subgraph instances[AWS Instance]
       n1(Instance1)
       n2(Instance2)
       n3(Instance3)
       nN(InstanceN)
end
subgraph prov[Provisioning]
       p1([wazuh-ansible])
       p2([wazuh-qa-ansible])
end
subgraph test[Testing]
       v1([builtin-taks])
       v2([custom-taks])
       v3([custom scripts])
       v4([pytest])
end
dep -.->instances
JenkinsNode -->|Provision|prov;
prov -->instances
JenkinsNode -->|Check|test;
test -->instances
```

### Advantages

#### Deployment and Provisioning

- Deployment easy to use
- Multiple OS support
- Support snapshots


#### System Test Framework

- If we end up using pytest again, we are familiar with it and some cases/code could be reused

### Disadvantages

#### Deployment and Provisioning

- Currenlty's wazuh-ansible dependant
- Provisioning can be hard to use

#### System Test Framework

- As ansible lacks in testing, we should create custom tasks to suply the builtin ones. Lastly, we would need custom scripts and/or pytest to be able to perform a nice testing (making us using something else instead of just ansible)
- Hard to create custom tasks. It is possible that some checks cannot be performed by just tasks.

**Comment by pro-akim** [comment]
# Approach with Terratest

Terratest is a testing framework that, although optimized for Terraform, can be used by integrating it (without Terraform) with Docker, AWS, Azure, Kubernetes, among others. Ideally, it should be integrated with Terraform to perform tests.

### Terraform
Terraform is a powerful tool that allows infrastructure to be provisioned and managed as code, with a large and active community support. By reviewing the documentation and conducting small tests, we can conclude the following:

## Advantages:

- Customization and parameterization of infrastructure through a pipeline: It is possible to achieve this. A template can be created to define the infrastructure to be created and receive parameters provided by Jenkins through a script.
- Execution of tests in a separate virtual machine: It is possible, but it would require a proof of concept (POC) to test it effectively.
- Management of EC2 instances and cloud infrastructure: This is also possible, as Terraform is designed for managing cloud infrastructure.

## Disadvantages:

- It would require rebuilding the entire testing framework from scratch.
- It would require a learning curve for the entire team.

To determine if this approach would work, a POC (proof of concept) should be conducted for a specific use case. Among the tests conducted so far, the following has been achieved:

- Testing Terratest with Terraform and Docker.
- Retrieving information from within the infrastructure using the framework.
- Integrating VirtualBox with Terraform to create infrastructure with virtual machines.

Keep in mind that further testing and evaluation are necessary to determine the feasibility and suitability of using Terratest and Terraform in the described context.

**Comment by roronoasins** [comment]
## KitchenCI

KitchenCI is a software development and infrastructure test automation tool. It is designed to simplify the writing and execution of integration tests and verification of infrastructure configurations.

### Advantages

- Consistent and reproducible deployments: KitchenCI allows you to define infrastructure configurations and provisioning steps in a declarative manner. This ensures that your deployments are consistent across different environments, reducing the risk of configuration drift and ensuring reproducibility.

- Automated provisioning: With KitchenCI, you can automate the provisioning of instances on various platforms such as AWS, Azure, or Vagrant. This saves time and effort by eliminating manual setup and configuration steps.

- Integration with configuration management tools: KitchenCI integrates seamlessly with popular configuration management tools like Ansible. This enables you to provision instances and apply desired configurations using familiar tools and workflows.

- Multi-environment support: KitchenCI supports testing and provisioning across multiple environments, such as development, staging, and production. You can define different suites or scenarios for each environment, allowing you to validate configurations and deployments before promoting them to production.

- Fast feedback loop: KitchenCI enables you to quickly iterate on your infrastructure configurations and deployments. By automating the provisioning process and running tests in isolated environments, you can receive feedback on the success or failure of your deployments rapidly, enabling faster troubleshooting and refinement.

- Scalability and flexibility: KitchenCI allows you to define and manage multiple instances in parallel, making it suitable for testing complex distributed systems or multi-node setups. You can easily scale your testing infrastructure as needed and run tests concurrently across different environments.

### Disadvantages


- Infrastructure requirements: KitchenCI relies on the availability of infrastructure resources such as virtual machines, remote hosts or containers to provision instances and run tests. This means you need to ensure the availability and management of these resources, which can add complexity and overhead to your testing environment.

- Maintenance overhead: As your infrastructure evolves and configurations change, you need to maintain and update your KitchenCI configuration files accordingly. This can introduce additional overhead in terms of managing and updating the provisioning scripts, test suites, and configuration files.

- Platform-specific considerations: Different platforms and providers may have their own quirks and limitations that you need to be aware of when using KitchenCI for deployment and provisioning. You may need to customize your configurations or scripts to accommodate platform-specific requirements.

- Not very extended community: When you need something not that standard you need to use some custom provisioner, for example. Which could not have official support. This relies in version limitations and errors that can't be solved because there is no information about them.

- Dependency on external tools: KitchenCI relies on external tools such as configuration management tools, provisioning tools, and test frameworks. This introduces dependencies on these tools and their compatibility with different platforms, which can sometimes lead to versioning or compatibility issues.

**Comment by Rebits** [comment]
### 30/05/2023

Meeting with @fcaffieri about current approach of system testing ecosystem. 
Pending update this issue with the conclusions and the improvements suggested in the meeting

**Comment by Rebits** [comment]
### 31/05/2023

During the meeting with @fcaffieri, we identified several issues that need to be addressed with our current approach:

- Addressing wazuh-ansible: We need to decide how to handle wazuh-ansible. We can consider options such as integrating it into our QA process, creating a separate repository, or incorporating it into Jenkins. We should have a discussion with the team to determine the best course of action.

- **Challenges with repository sharing**: We are facing difficulties when sharing the repository other teams. To resolve this, we can explore sharing the necessary tools or copying them into the QA module to ensure smoother collaboration.

- **Managing Jenkins saturation**: We need to tackle the issue of Jenkins becoming overloaded. With the addition of more testing processes, it is crucial to find a solution to prevent Jenkins from being overwhelmed.

In addition to addressing these issues, we discussed some valuable enhancements for our current framework:

- **Creation of a user-friendly web server**: It would be beneficial to develop a web server or a similar solution that provides a more user-friendly interface for executing pipelines. This platform could also incorporate documentation and enable dynamic customization of test parameters, enhancing our testing capabilities.

-  **Implementation of a Kibana dashboard**: To better track and analyze our CI processes (nightly, weekly, release), we propose building a Kibana dashboard. This dashboard would record the reports generated by our tests and allow for easy comparison of results, including footprint, performance, and more, across different versions of our software.

By addressing these issues and implementing these enhancements, we can improve the efficiency and effectiveness of our development and testing processes.
